// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBxDi3LsWCnrkNAVgO6Jf0XZ3mtgZN9mM',
    appId: '1:689056120880:web:33a368219b83d97508adf5',
    messagingSenderId: '689056120880',
    projectId: 'keahi-social-flutter',
    authDomain: 'keahi-social-flutter.firebaseapp.com',
    storageBucket: 'keahi-social-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJh-tNgTJUsNaqdPtd38WxizBU8S_E12w',
    appId: '1:689056120880:android:29cd39625ea7ca6c08adf5',
    messagingSenderId: '689056120880',
    projectId: 'keahi-social-flutter',
    storageBucket: 'keahi-social-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBppjPJf0eX6_vau09h-a8CCrbbzO7eyEM',
    appId: '1:689056120880:ios:dd74daf75192e69908adf5',
    messagingSenderId: '689056120880',
    projectId: 'keahi-social-flutter',
    storageBucket: 'keahi-social-flutter.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBppjPJf0eX6_vau09h-a8CCrbbzO7eyEM',
    appId: '1:689056120880:ios:dd74daf75192e69908adf5',
    messagingSenderId: '689056120880',
    projectId: 'keahi-social-flutter',
    storageBucket: 'keahi-social-flutter.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBxDi3LsWCnrkNAVgO6Jf0XZ3mtgZN9mM',
    appId: '1:689056120880:web:a32f25083b2be51308adf5',
    messagingSenderId: '689056120880',
    projectId: 'keahi-social-flutter',
    authDomain: 'keahi-social-flutter.firebaseapp.com',
    storageBucket: 'keahi-social-flutter.firebasestorage.app',
  );
}
